### ISSUE TITLE
HTML Links

### ISSUE THREAD

**Issue by DeadshotMaster** [bmorelli25/Become-A-Full-Stack-Web-Developer#14]
Add this to HTML Section.

Helpful Learning Tutorials:

http://www.html5tutorial.info - HTML5 Specifically
https://www.lynda.com/HTML-tutorials/Welcome/170427/196125-4.html

Code Snippets:

https://codegeekz.com/10-best-html5-code-snippets-to-simplify-you-tasks/
http://www.makeuseof.com/tag/7-cool-html-effects-that-anyone-can-add-to-their-website-nb/

**Comment by bmorelli25** [comment]
Already talking about HTML additions in #7 . Please add your recommendations there.. thanks!
