### ISSUE TITLE
Maybe add a section on editors?

### ISSUE THREAD

**Issue by TylerWalker12** [bmorelli25/Become-A-Full-Stack-Web-Developer#17]

**Comment by bmorelli25** [comment]
For now, I'm going to leave this off. A good thought to come back to later. Thanks.

**Comment by bmorelli25** [comment]
Coming back to this. Anyone want to take this on?

**Comment by mrsmoo** [comment]
I can help, have been using many editors and can recommend some .

**Comment by Kartikkh** [comment]
Do i Add editors Section also ?

**Comment by bmorelli25** [comment]
Yes, feel free

**Comment by Kartikkh** [comment]
Pls check for Issue ! i have cleared that !

**Comment by bmorelli25** [comment]
Closed with #41
