### ISSUE TITLE
Update resource web development summary video

### ISSUE THREAD

**Issue by alvarosevilla95** [bmorelli25/Become-A-Full-Stack-Web-Developer#3]
In the first section, the resource at:
Youtube video outlining what to learn (similar to above, but in video format) - Watch this if you want to become a web developer (https://www.youtube.com/watch?v=pB0WvcxTbCA)

seems to have an update version here https://www.youtube.com/watch?v=sBzRwzY7G-k

**Comment by bmorelli25** [comment]
Ahh good catch! Do you want to create a PR for this?

**Comment by bmorelli25** [comment]
updated
