### ISSUE TITLE
Add resources to learn html

### ISSUE THREAD

**Issue by Roshanjossey** [bmorelli25/Become-A-Full-Stack-Web-Developer#7]
We need materials in [this section](https://github.com/bmorelli25/Become-A-Full-Stack-Web-Developer#learn-html)

I used [this material](http://learn.shayhowe.com/html-css/) to learn HTML. Even now, I go back to basics at times and revisit the same resources.

I'd be happy to add this if it'd add enough value.

**Comment by asantos3** [comment]
MDN is always good too so maybe add [this](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML) too.

**Comment by tritims** [comment]
This HTML course from [sololearn ](https://www.sololearn.com/Course/HTML/)is a good one too

**Comment by bmorelli25** [comment]
Does someone want to create a PR with all of these links? MDN should be at the top in my opinion. Whadya think?

**Comment by Roshanjossey** [comment]
@bmorelli25: I'd love to take that up.

I agree with you on your opinion that MDN should go first

I'll do it in this order

MDN
ShayHowe
Sololearn

**Comment by Roshanjossey** [comment]
Thank you @asantos3 and @tritims for your suggestions.

![Thank you](https://cloud.githubusercontent.com/assets/8488446/24109160/d414555c-0db5-11e7-8957-e9dd54dd1e18.png)

**Comment by FlyingHouse47** [comment]
The SoloLearn course is very beginner friendly. MDN also helped me a lot.

**Comment by Roshanjossey** [comment]
@FlyingHouse47: I've submitted a PR to add Mozilla docs and Shayhowe's material.

How about you submit another PR to add SoloLearn? We can continue to discuss about material for this section and add those as well

**Comment by bmorelli25** [comment]
See #15
